# This is a basic workflow to help you get started with Actions
name: Pull data

# Controls when the workflow will run
on:
  schedule:
    - cron:  '*/10 * * * *' # Every 10 minutes. Ref https://crontab.guru/examples.html
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Set up configurations
        shell: bash
        run: echo -n "${{ secrets.SHEET_KEY }}" | base64 --decode > key.json

      # Runs a single command using the runners shell
      - name: Get spreadsheet data
        run: node ./pullData.js
        
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add test.json
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push origin HEAD

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
